name: update-changelog

on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-tag: ${{ github.event.release.tag_name }}
          generate-url: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update changelog for release ${{ github.event.release.tag_name }}